clients:
  - url: "http://localhost:10000/api"
    requestFile: "./data/request.json"
    callsNumber: 20
  - url: "http://localhost:10001/api2"
    requestFile: "./data/request.json"
    callsNumber: 10

servers:
  - port: "10000"
    host: "localhost"
    path: "/api"
    healthcheckPath: "/healthcheck"
    responseFile: "./data/response.json"
    healthcheckFile: "./data/healthcheck.json"
  - port: "10001"
    host: "localhost"
    path: "/api2"
    healthcheckPath: "/healthcheck"
    responseFile: "./data/response.json"
    healthcheckFile: "./data/healthcheck.json"
